from __future__ import annotations

import importlib

import pytest

PUBLIC_MODULES = [
    'jester',
    'jester.ai',
    'jester.ai.adapters',
    'jester.ai.base',
    'jester.ai.classification',
    'jester.ai.contracts',
    'jester.ai.reasoning',
    'jester.ai.registry',
    'jester.ai.selection',
    'jester.api',
    'jester.api.app',
    'jester.api.deps',
    'jester.api.frontend',
    'jester.api.routers.health',
    'jester.api.routers.live_dm',
    'jester.api.routers.prep',
    'jester.api.routers.retrieval',
    'jester.api.routers.sessions',
    'jester.api.routers.teaching',
    'jester.api.schemas',
    'jester.app',
    'jester.app.application',
    'jester.app.capabilities',
    'jester.app.contracts',
    'jester.app.contracts.common',
    'jester.app.contracts.live_dm',
    'jester.app.contracts.prep',
    'jester.app.contracts.teaching',
    'jester.app.live_dm',
    'jester.app.orchestration',
    'jester.app.orchestration.contracts',
    'jester.app.orchestration.policy',
    'jester.app.orchestration.prompting',
    'jester.app.orchestration.retrieval',
    'jester.app.prep',
    'jester.app.prompting',
    'jester.app.router',
    'jester.app.session_templates',
    'jester.app.sessions',
    'jester.app.teaching',
    'jester.app.visibility',
    'jester.config.settings',
    'jester.corpus.jsonl',
    'jester.corpus.models',
    'jester.domain',
    'jester.domain.actions',
    'jester.domain.combat',
    'jester.domain.entities',
    'jester.domain.memory',
    'jester.domain.session',
    'jester.engine',
    'jester.engine.combat',
    'jester.engine.memory',
    'jester.engine.narration',
    'jester.engine.pipeline',
    'jester.engine.privacy',
    'jester.engine.rules',
    'jester.engine.rules.action_economy',
    'jester.engine.rules.attacks',
    'jester.engine.rules.capability',
    'jester.engine.rules.movement',
    'jester.engine.scenario',
    'jester.ingestion.filtering',
    'jester.observability',
    'jester.observability.logging',
    'jester.processing.sanitizer',
    'jester.prompts.registry',
    'jester.retrieval.contracts',
    'jester.retrieval.orchestrator',
    'jester.retrieval.service',
    'jester.retrieval.vector',
    'jester.state.store',
    'jester.validation.output_validator',
]


@pytest.mark.parametrize('module_name', PUBLIC_MODULES)
def test_public_modules_import_cleanly(module_name: str) -> None:
    imported = importlib.import_module(module_name)
    assert imported is not None

